# Generated by Django 5.0.6 on 2026-04-23 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('odometer_in', models.PositiveIntegerField(blank=True, null=True)),
                ('inspection_notes', models.TextField(blank=True, help_text='Issues observed during inspection')),
                ('work_to_do', models.TextField(blank=True, help_text='List of works to be carried out')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('billed', 'Billed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('labor_rate', models.DecimalField(decimal_places=2, default=400, help_text='Per hour', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobcards', to='customers.customer')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobcards', to='customers.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='jobcards.jobcard')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.part')),
            ],
        ),
    ]
