# Generated by Django 4.2.30 on 2026-05-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='battery_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='service_advisor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='tyres_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wa_audio',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('nw', 'Not working/missing'), ('dd', 'Dent/Damage/Scratch/Dots')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wa_cd_pendrive',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('nw', 'Not working/missing'), ('dd', 'Dent/Damage/Scratch/Dots')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wa_central_locking',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('nw', 'Not working/missing'), ('dd', 'Dent/Damage/Scratch/Dots')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wa_idol',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('nw', 'Not working/missing'), ('dd', 'Dent/Damage/Scratch/Dots')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wa_jack',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('nw', 'Not working/missing'), ('dd', 'Dent/Damage/Scratch/Dots')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wa_mat',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('nw', 'Not working/missing'), ('dd', 'Dent/Damage/Scratch/Dots')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wa_perfume',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('nw', 'Not working/missing'), ('dd', 'Dent/Damage/Scratch/Dots')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wa_spare_wheel',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('nw', 'Not working/missing'), ('dd', 'Dent/Damage/Scratch/Dots')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wa_steering',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('nw', 'Not working/missing'), ('dd', 'Dent/Damage/Scratch/Dots')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wa_toolkit',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('nw', 'Not working/missing'), ('dd', 'Dent/Damage/Scratch/Dots')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wa_warranty_book',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('nw', 'Not working/missing'), ('dd', 'Dent/Damage/Scratch/Dots')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wa_wheel_cap',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('nw', 'Not working/missing'), ('dd', 'Dent/Damage/Scratch/Dots')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wa_windshield',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('nw', 'Not working/missing'), ('dd', 'Dent/Damage/Scratch/Dots')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='work_to_do',
            field=models.TextField(blank=True, help_text='Job description / work requested'),
        ),
    ]
