# Generated by Django 5.0.6 on 2026-04-23 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike / Motorcycle'), ('scooter', 'Scooter'), ('suv', 'SUV'), ('truck', 'Truck'), ('auto', 'Auto-Rickshaw'), ('other', 'Other')], default='car', max_length=20)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=60)),
                ('chassis_number', models.CharField(blank=True, max_length=60)),
                ('odometer', models.PositiveIntegerField(default=0, help_text='Last recorded km')),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('pollution_expiry', models.DateField(blank=True, null=True)),
                ('rc_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.customer')),
            ],
        ),
    ]
