# Generated by Django 4.2 on 2026-06-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike / Motorcycle'), ('scooter', 'Scooter'), ('suv', 'SUV'), ('truck', 'Truck'), ('auto', 'Auto-Rickshaw'), ('other', 'Other')], default='car', max_length=20),
        ),
    ]
