# Generated by Django 4.2 on 2026-06-03 11:20

from django.db import migrations


def fix_vehicle_types(apps, schema_editor):
    Vehicle = apps.get_model('customers', 'Vehicle')
    for vehicle in Vehicle.objects.all():
        if vehicle.vehicle_type and vehicle.vehicle_type.isupper():
            vehicle.vehicle_type = vehicle.vehicle_type.lower()
            vehicle.save()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.RunPython(fix_vehicle_types),
    ]
